version: '3.8'

services:
  bot:
    build: .
    container_name: selectionway-bot
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
